//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Jiki.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_CHOOSE_GAME                 101
#define IDR_MAINFRAME                   128
#define IDR_SEJIKITYPE                  129
#define IDI_SEJIKE                      129
#define IDC_ROTATE                      131
#define IDR_GAME_1                      137
#define IDR_GAME_2                      138
#define IDR_GAME_3                      139
#define IDR_GAME_4                      140
#define IDR_GAME_5                      141
#define IDR_GAME_6                      142
#define IDR_GAME_7                      143
#define IDR_GAME_8                      144
#define IDR_GAME_9                      145
#define IDR_GAME_10                     146
#define IDR_GAME_11                     147
#define IDR_GAME_12                     148
#define IDB_WOOD                        150
#define IDB_TRIA                        163
#define IDD_REGISTER                    164
#define IDD_DLG_REG                     164
#define IDB_EYES                        165
#define IDB_KEY_TEXT                    166
#define IDI_ICON1                       169
#define IDC_HYPERLINK                   1000
#define IDC_BREAK_BEGINNER              1011
#define IDC_BREAK_CLEVER                1012
#define IDC_BREAK_IMPOS                 1013
#define IDC_BUT_REG                     1020
#define IDC_EDIT_NAME                   1021
#define IDC_EDIT_CODE                   1022
#define IDC_BREAK_REGISTER              1023
#define IDC_BREAK_USER                  1025
#define IDC_BUT_CLOSE                   1026
#define ID_HELP_HOWTOPLAY               32771
#define ID_HELP_REGISTERSEJIKI          32772
#define ID_REGISTER                     32772
#define ID_FILE_SAVEAS                  32774
#define ID_NEW_GAME                     32778
#define ID_VIEW_GRID                    32779
#define ID_VIEW_INDEX                   32780
#define ID_VIEW_SPIN                    32781
#define IDS_GRID                        57682
#define IDS_DIMS                        57683
#define IDS_ROWS                        57683
#define IDS_COVERED                     57684
#define IDS_COLS                        57685

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
